build:
  image: golang:1.17-alpine
  when: manual
  stage: build
  variables:
    VERSION: 0.55.6
  script:
    - cd backlinker
    - go run main.go
    - cd ..
    - apk --no-cache add curl
    - curl --location --output hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz"
    - tar -zxvf hugo.tar.gz
    - ./hugo
  artifacts:
    paths:
      - public/
    expire_in: 1 day

deploy:
  image: ubuntu:latest
  when: manual
  stage: deploy
  needs: [build]
  script:
  - apt-get update -yqq
  - apt-get install -yqq lftp ca-certificates
  - update-ca-certificates
  - lftp -e "open $FTP_HOST; user $FTP_USER $FTP_PW; mkdir -f staging; mirror -X .* -X .*/ --reverse --verbose --delete public/ .; bye"
  environment:
    name: production
    url: https://ninetyfour.ch
