deploy:
  image: golang:1.17-alpine
  stage: deploy

  only:
    refs:
      - main

  variables:
    VERSION: 0.80.0

  script:
    - apk --no-cache add curl lftp
    - cd backlinker
    - go run main.go
    - cd ..
    - curl --location --output hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz"
    - tar -zxvf hugo.tar.gz
    - ./hugo
    - lftp -e "open $FTP_HOST; user $FTP_USER $FTP_PW; mkdir -f staging; mirror -X .* -X .*/ --reverse --verbose --delete public/ httpdocs/; bye"

  environment:
    name: production
    url: https://ninetyfour.ch

