deploy:
  image: golang:alpine
  stage: deploy

  # only build on main branch
  only:
    refs:
      - main

  script:
    # install hugo to generate the website
    - go install github.com/gohugoio/hugo@latest
    - ./hugo --minify

    # install lftp for the file transfer
    - apk --no-cache add lftp
    - lftp -e "open $FTP_HOST; user $FTP_USER $FTP_PW; mkdir -f staging; mirror -X .* -X .*/ --reverse --verbose --delete public/ httpdocs/; bye"

  environment:
    name: production
    url: https://ninetyfour.ch

