baseURL: "https://ninetyfour.ch/"
languageCode: "en-us"
title: "tales of meandering code"

params:
  description: "Notes from the collision of code and reality."

menu:
  main:
    - name: Blogposts
      url: /posts
    - name: Zettelkasten
      url: /zettelkasten
    - name: Listen & Read 
      url: /listenandread
    - name: About
      url: /about
    - name: Projects
      url: /projects
