baseURL: "https://ninetyfour.ch/"
languageCode: "en-us"
title: "tales of meandering code"

menu:
  main:
    - name: Blogposts
      url: /posts
    - name: Zettelkasten
      url: /zettelkasten
    - name: Listen & Read 
      url: /listenandread
    - name: Projects
      url: /projects
